feat: Create React app + install Tailwind CSS
WG-CC/transitiontoolkit-frontend pull request #7
Opened 2024-04-20 00:50 UTC by hccleveland

# Description

- Set up React and TypeScript with Vite using yarn.
- Installed and implemented Tailwind CSS.
- Removed unnecessary code and files from React project install.
- Added documentation for prerequisites and setup.

# Closes issue(s)

Resolves #1 

# How to test

From the branch, run:
1. `yarn`
2. `yarn dev`

The app can be viewed at http://localhost:5173. 
From there, "Hello world!" should be seen with Tailwind styling implemented. (Large font, bold, and underlined)

# Changes include

1. yarn set as package manager.
2. React and TypeScript with Vite
3. Tailwind CSS

# Checklist

- [X] I have tested this code
- [X] I have updated the README

2024-04-23 07:02 UTC, Anissa3005 approved these changes
Looks Great! ✨
I have added some comments. 

- I also think it's better to not use an extra file `transitiontool-kitfrontend`. Everything in that file I would move to the root. I think by using an extra file it adds more complexity later on the project.
- I think we also missing an `.yarnrc.yaml` file, when I run yarn it creates it automatically for me. (I always have worked with yarn yaml file, but maybe there is an other approach?)

2024-04-23 07:09 UTC, Anissa3005 requested changes
Sorry I made a mistake, I had to request changes instead of approve.

2024-04-24 00:35 UTC, hccleveland commented on README.md
> +- [yarn](https://yarnpkg.com/)
I've added this information as a callout below, along with the steps for installing yarn. If this is overkill, or if you want changes from the update, please let me know.

2024-04-24 00:42 UTC, hccleveland commented on transitiontoolkit-frontend/package.json
> +  "dependencies": {
Implementing `.yarnrc.yaml` added yarn's version as `packageManager` to the `package.JSON` file. For `node`, what version(s) do we want to specify for this?

2024-04-24 02:42 UTC, Anissa3005 commented on transitiontoolkit-frontend/package.json
> +  "dependencies": {
In the `.yarnrc.yaml` you point than to `nodeLinker: node-modules`. Since when I run yarn on your branch it would create that file automatically. Maybe by including it we make sure it doesn't created that file every time we run yarn.

I would go with he newest stable `node` version, same for `yarn`.

2024-04-24 02:42 UTC, Anissa3005 commented on README.md
> +- [yarn](https://yarnpkg.com/)
I think it's okay to add to run `corepack enable` to be able to use `yarn`

2024-04-24 02:42 UTC, Anissa3005 commented on README.md
> +- [yarn](https://yarnpkg.com/)
Also the README titles were just as guideline, if you think we should add or changes titles please do! 🙏

2024-05-17 06:31 UTC, NabbeunNabi commented
LGTM. Tested locally and following the read me works

2024-05-17 06:32 UTC, NabbeunNabi approved these changes

2024-05-22 03:26 UTC, kyougene approved these changes
LGTM, works locally on mac

2024-06-03 04:28 UTC, Anissa3005 approved these changes
LGTM

2024-06-03 04:57 UTC, merged